---
title: "NBA Salary Demo 1"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(leaps)
library(gridExtra)
library(cowplot)
library(corrplot)
library(reshape2)
library(ggplot2)
library(car)
library(glmnet)
library(GGally)
library(olsrr)
library(ggcorrplot)
library(knitr)
library(BBmisc)
library(cluster)
library(factoextra)
```


```{r} 
#Read CSV
nba <- read.csv("dataxnba.csv")
nba <- filter(nba, Season >= 2000)
#Remove duplicates
nba <- nba[!duplicated(nba$Player), ]
rownames(nba) <- nba[,1]
nba <- nba[,-1]

#Filter by position
pg <- filter(nba, Pos == "PG" | Pos == "PG-SG" | Pos == "SG-PG" | Pos == "PG-SF" )
sg <- filter(nba, Pos == "SG" | Pos == "SF-SG" | Pos == "SG-PG" | Pos == "SG-PF" | Pos == "PG-SG" | Pos == "SG-SF")
sf <- filter(nba, Pos == "SF" | Pos == "PG-SF" | Pos == "PF-SF" | Pos == "SF-SG" | Pos == "SF-PF" | Pos == "SG-SF" | Pos == "SF-C" )
pf <- filter(nba, Pos == "PF" | Pos == "SF-PF" | Pos == "PF-SF" | Pos == "PF-C" | Pos == "C-PF" )
c <- filter(nba, Pos == "C" | Pos == "C-PF" | Pos == "PF-C" | Pos == "SF-C" )
```

```{r, echo = FALSE, message=FALSE}

#Plot histogram of average (inflated) salary by season for the entire nba + all positions (6 total)
g1 <- ggplot(nba) + geom_bar(aes(x = Season, y =SalaryIn), stat = "summary", fill = "steelblue") + ylab("Average Salary")
g2 <- ggplot(pg) + geom_bar(aes(x = Season, y =SalaryIn), stat = "summary", fill = "steelblue") + ylab("PG Avg Salary")
g3 <- ggplot(sg) + geom_bar(aes(x = Season, y =SalaryIn), stat = "summary", fill = "steelblue") + ylab("SG Avg Salary")
g4 <- ggplot(sf) + geom_bar(aes(x = Season, y =SalaryIn), stat = "summary", fill = "steelblue") + ylab("SF Avg Salary")
g5 <- ggplot(pf) + geom_bar(aes(x = Season, y =SalaryIn), stat = "summary", fill = "steelblue") + ylab("PF Avg Salary")
g6 <- ggplot(c) + geom_bar(aes(x = Season, y =SalaryIn), stat = "summary", fill = "steelblue") + ylab("C Avg Salary")

grid.arrange(g1, g2, g3, g4, g5, g6, ncol= 2)

#Plot histogram of average pCap by season for the entire nba + all positions (6 total)
g7 <- ggplot(nba) + geom_bar(aes(x = Season, y =pCap), stat = "summary", fill = "steelblue") + ylab("Average Salary")
g8 <- ggplot(pg) + geom_bar(aes(x = Season, y =pCap), stat = "summary", fill = "steelblue") + ylab("PG Avg Salary")
g9 <- ggplot(sg) + geom_bar(aes(x = Season, y =pCap), stat = "summary", fill = "steelblue") + ylab("SG Avg Salary")
g10 <- ggplot(sf) + geom_bar(aes(x = Season, y =pCap), stat = "summary", fill = "steelblue") + ylab("SF Avg Salary")
g11 <- ggplot(pf) + geom_bar(aes(x = Season, y =pCap), stat = "summary", fill = "steelblue") + ylab("PF Avg Salary")
g12 <- ggplot(c) + geom_bar(aes(x = Season, y =pCap), stat = "summary", fill = "steelblue") + ylab("C Avg Salary")

grid.arrange(g7, g8, g9, g10, g11, g12, ncol= 2)
```

```{r, echo = FALSE, message=FALSE}
#Plot correlation matrix for all positions with these selected variables (you can ignore par() function, just create plots for each pos )
par(mfrow=c(1,1))

corrplot(cor(pg %>% select(Age, FG, FGA, FGP, X3PM, X3PA, X3PP, X2PM, X2PA, X2PP, eFG, FTM, FTA, FTP, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, PER, TS, X3PAr, FTr, USG, OWS, DWS, WS, WS48, OBPM, DBPM, BPM, OWS, DWS, VORP, pCap), use = "complete.obs"), method = "color", type = "upper", tl.cex=0.5)
mtext("PG Corr Plot", at=2.5, line=-10.5, cex=1)

par(mfrow=c(2,2))

corrplot(cor(sg %>% select(Age, FG, FGA, FGP, X3PM, X3PA, X3PP, X2PM, X2PA, X2PP, eFG, FTM, FTA, FTP, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, PER, TS, X3PAr, FTr, USG, OWS, DWS, WS, WS48, OBPM, DBPM, BPM, OWS, DWS, VORP, pCap), use = "complete.obs"), method = "color", type = "upper", tl.cex=0.5)
mtext("SG Corr Plot", at=2.5, line=-8.5, cex=1)

corrplot(cor(sf %>% select(Age, FG, FGA, FGP, X3PM, X3PA, X3PP, X2PM, X2PA, X2PP, eFG, FTM, FTA, FTP, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, PER, TS, X3PAr, FTr, USG, OWS, DWS, WS, WS48, OBPM, DBPM, BPM, OWS, DWS, VORP, pCap), use = "complete.obs"), method = "color", type = "upper", tl.cex=0.5)
mtext("SF Corr Plot", at=2.5, line=-8.5, cex=1)

corrplot(cor(pf %>% select(Age, FG, FGA, FGP, X3PM, X3PA, X3PP, X2PM, X2PA, X2PP, eFG, FTM, FTA, FTP, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, PER, TS, X3PAr, FTr, USG, OWS, DWS, WS, WS48, OBPM, DBPM, BPM, OWS, DWS, VORP, pCap), use = "complete.obs"), method = "color", type = "upper", tl.cex=0.5)
mtext("PF Corr Plot", at=2.5, line=-8.5, cex=1)

corrplot(cor(c %>% select(Age, FG, FGA, FGP, X3PM, X3PA, X3PP, X2PM, X2PA, X2PP, eFG, FTM, FTA, FTP, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, PER, TS, X3PAr, FTr, USG, OWS, DWS, WS, WS48, OBPM, DBPM, BPM, OWS, DWS, VORP, pCap), use = "complete.obs"), method = "color", type = "upper", tl.cex=0.5)
mtext("C Corr Plot", at=2.5, line=-8.5, cex=1)
```

```{r, echo = FALSE, message=FALSE}
#Create a copy of nba + all positions and keep only these variables in the copy
nbacopy <- subset(nba, select = -c(Season, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, SalaryIn, Cap, Experience))

pgcopy <- subset(pg, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG,  BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, SalaryIn, Cap, Experience))

sgcopy <- subset(sg, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG,  BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, SalaryIn, Cap, Experience))

sfcopy <- subset(sf, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, SalaryIn, Cap, Experience))

pfcopy <- subset(pf, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, SalaryIn, Cap, Experience))

ccopy <- subset(c, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG,  BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, SalaryIn, Cap, Experience))


set.seed(999)

#RANDOM SPLIT FOR PG
smp_sizepg <- floor(0.75 * nrow(pgcopy))
train_indpg <- sample(seq_len(nrow(pgcopy)), size = smp_sizepg)
trainpg <- pgcopy[train_indpg, ]
testpg <- pgcopy[-train_indpg, ]

#RANDOM SPLIT FOR SG
smp_sizesg <- floor(0.75 * nrow(sgcopy))
train_indsg <- sample(seq_len(nrow(sgcopy)), size = smp_sizesg)
trainsg <- sgcopy[train_indsg, ]
testsg <- sgcopy[-train_indsg, ]

#RANDOM SPLIT FOR SF
smp_sizesf <- floor(0.75 * nrow(sfcopy))
train_indsf <- sample(seq_len(nrow(sfcopy)), size = smp_sizesf)
trainsf <- sfcopy[train_indsf, ]
testsf <- sfcopy[-train_indsf, ]

#RANDOM SPLIT FOR PF
smp_sizepf <- floor(0.75 * nrow(pfcopy))
train_indpf <- sample(seq_len(nrow(pfcopy)), size = smp_sizepf)
trainpf <- pfcopy[train_indpf, ]
testpf <- pfcopy[-train_indpf, ]

#RANDOM SPLIT FOR CENTER
smp_sizecenter <- floor(0.75 * nrow(ccopy))
train_indcenter <- sample(seq_len(nrow(ccopy)), size = smp_sizecenter)
traincenter <- ccopy[train_indcenter, ]
testcenter <- ccopy[-train_indcenter, ]
```

```{r}
#I created an R squared function,
rsq <- function (true, predicted)
{
  SSE <- sum((predicted - true)^2)
  SST <- sum((true - mean(true))^2)
  R_square <- 1 - SSE / SST
}

#I created a dataframe to store the future results
modelResults <- setNames(data.frame(matrix(ncol = 4, nrow = 0)), c("Model", "R2", "RMSE", "MAE"))
```

```{r, echo = FALSE, message=FALSE}
#LASSO FOR PG

#Here i split train, test x and y
xpgtrain <- model.matrix(pCap ~.^2 , trainpg)[,-1]
xpgtest <- model.matrix(pCap ~.^2 , testpg)[,-1]
ypgtrain <- trainpg$pCap
ypgtest <- testpg$pCap

lambdas <- 10^seq(2, -3, by = -.1)

cvpg <- cv.glmnet(x = xpgtrain, y = ypgtrain, alpha = 1, lambda = lambdas, nfolds = 5, family = "gaussian")
bestlampg <- cvpg$lambda.min
lassopg <- glmnet(x = xpgtrain, ypgtrain, alpha = 1, lambda = bestlampg)
predpgtrain <- predict(lassopg, s = bestlampg, newx = xpgtrain)
predpgtest <- predict(lassopg, s = bestlampg, newx = xpgtest)

coef(lassopg)

#Adding result to my dataframe from earlier
lassoPGtrain <- data.frame(Model = "lassoPGtrain", R2 = rsq(ypgtrain, predpgtrain), RMSE = RMSE(ypgtrain, predpgtrain), MAE = MAE(ypgtrain, predpgtrain))
lassoPGtest <- data.frame(Model = "lassoPGtest",R2 = rsq(ypgtest, predpgtest), RMSE = RMSE(ypgtest, predpgtest), MAE = MAE(ypgtest, predpgtest))

modelResults <- rbind(modelResults, lassoPGtrain)
modelResults <- rbind(modelResults, lassoPGtest)
```

```{r, echo = FALSE, message=FALSE}
xsgtrain <- model.matrix(pCap ~.^2 , trainsg)[,-1]
xsgtest <- model.matrix(pCap ~.^2 , testsg)[,-1]
ysgtrain <- trainsg$pCap
ysgtest <- testsg$pCap

cvsg <- cv.glmnet(x = xsgtrain, y = ysgtrain, alpha = 1, lambda = lambdas, nfolds = 5, family = "gaussian")
bestlamsg <- cvsg$lambda.min
lassosg <- glmnet(x = xsgtrain, ysgtrain, alpha = 1, lambda = bestlamsg)
predsgtrain <- predict(lassosg, s = bestlamsg, newx = xsgtrain)
predsgtest <- predict(lassosg, s = bestlamsg, newx = xsgtest)

coef(lassosg)

lassoSGtrain <- data.frame(Model = "lassoSGtrain", R2 = rsq(ysgtrain, predsgtrain), RMSE = RMSE(ysgtrain, predsgtrain), MAE = MAE(ysgtrain, predsgtrain))
lassoSGtest <- data.frame(Model = "lassoSGtest", R2 = rsq(ysgtest, predsgtest), RMSE = RMSE(ysgtest, predsgtest), MAE = MAE(ysgtest, predsgtest))

modelResults <- rbind(modelResults, lassoSGtrain)
modelResults <- rbind(modelResults, lassoSGtest)
```

```{r, echo = FALSE, message=FALSE}
xsftrain <- model.matrix(pCap ~.^2 , trainsf)[,-1]
xsftest <- model.matrix(pCap ~.^2 , testsf)[,-1]
ysftrain <- trainsf$pCap
ysftest <- testsf$pCap

lambdas <- 10^seq(2, -3, by = -.1)
cvsf <- cv.glmnet(x = xsftrain, y = ysftrain, alpha = 1, lambda = lambdas, nfolds = 5, family = "gaussian")
bestlamsf <- cvsf$lambda.min
lassosf <- glmnet(x = xsftrain, ysftrain, alpha = 1, lambda = bestlamsf)
predsftrain <- predict(lassosf, s = bestlamsf, newx = xsftrain)
predsftest <- predict(lassosf, s = bestlamsf, newx = xsftest)

coef(lassosf)

lassoSFtrain <- data.frame(Model = "lassoSFtrain", R2 = rsq(ysftrain, predsftrain), RMSE = RMSE(ysftrain, predsftrain), MAE = MAE(ysftrain, predsftrain))
lassoSFtest <- data.frame(Model = "lassoSFtest", R2 = rsq(ysftest, predsftest), RMSE = RMSE(ysftest, predsftest), MAE = MAE(ysftest, predsftest))

modelResults <- rbind(modelResults, lassoSFtrain)
modelResults <- rbind(modelResults, lassoSFtest)
```

```{r, echo = FALSE, message=FALSE}
xpftrain <- model.matrix(pCap ~.^2 , trainpf)[,-1]
xpftest <- model.matrix(pCap ~.^2 , testpf)[,-1]
ypftrain <- trainpf$pCap
ypftest <- testpf$pCap

cvpf <- cv.glmnet(x = xpftrain, y = ypftrain, alpha = 1, lambda = lambdas, nfolds = 5, family = "gaussian")
bestlampf <- cvpf$lambda.min
lassopf <- glmnet(x = xpftrain, ypftrain, alpha = 1, lambda = bestlampf)
predpftrain <- predict(lassopf, s = bestlampf, newx = xpftrain)
predpftest <- predict(lassopf, s = bestlampf, newx = xpftest)

coef(lassopf)

lassoPFtrain <- data.frame(Model = "lassoPFtrain", R2 = rsq(ypftrain, predpftrain), RMSE = RMSE(ypftrain, predpftrain), MAE = MAE(ypftrain, predpftrain))
lassoPFtest <-  data.frame(Model = "lassoPFtest", R2 = rsq(ypftest, predpftest), RMSE = RMSE(ypftest, predpftest), MAE = MAE(ypftest, predpftest))

modelResults <- rbind(modelResults, lassoPFtrain)
modelResults <- rbind(modelResults, lassoPFtest)
```

```{r, echo = FALSE, message=FALSE}
xctrain <- model.matrix(pCap ~.^2 , traincenter)[,-1]
xctest <- model.matrix(pCap ~.^2 , testcenter)[,-1]
yctrain <- traincenter$pCap
yctest <- testcenter$pCap


cvc <- cv.glmnet(x = xctrain, y = yctrain, alpha = 1, lambda = lambdas, nfolds = 5, family = "gaussian")
bestlamc <- cvc$lambda.min
lassoc <- glmnet(x = xctrain, yctrain, alpha = 1, lambda = bestlamc)
predctrain <- predict(lassoc, s = bestlamc, newx = xctrain)
predctest <- predict(lassoc, s = bestlamc, newx = xctest)

coef(lassoc)

lassoCtrain <- data.frame(Model = "lassoCtrain", R2 = rsq(yctrain, predctrain), RMSE = RMSE(yctrain, predctrain), MAE = MAE(yctrain, predctrain))
lassoCtest <- data.frame(Model = "lassoCtest", R2 = rsq(yctest, predctest), RMSE = RMSE(yctest, predctest), MAE = MAE(yctest, predctest))

modelResults <- rbind(modelResults, lassoCtrain)
modelResults <- rbind(modelResults, lassoCtest)
```


```{r, echo = FALSE, message=FALSE}

#RFE variable selection

set.seed(1)
control <- rfeControl(functions=lmFuncs, method="cv", number=10)
pgvar <- rfe(pgcopy[,1:22], pgcopy[,23], sizes=c(1:22), rfeControl=control)
predictors(pgvar)
plot(pgvar, type=c("g", "o"))


#I create another copy of the copy. In this new copy I keep the variables that were selected from the RFE. Repeat for all positions
pgcopy2 <- pgcopy %>% select(TS, FGP, FTP, X3PM, X3PP, FTr, PF, FTA, DRB, ORB, STL, AST, BLK, PER, FTM, Age, TOV, PTS, X3PAr, pCap)

sgvar <- rfe(sgcopy[,1:22], sgcopy[,23], sizes=c(1:22), rfeControl=control)
predictors(sgvar)
plot(sgvar, type=c("g", "o"))

sgcopy2 <- sgcopy %>% select(TS, FTP, FGP, BLK, X3PAr, TOV, FTr, PF, DRB, STL, X3PM, FTM, ORB,PER, PTS, Age, X3PM, FTA, AST, OWS, pCap)

sfvar <- rfe(sfcopy[,1:22], sfcopy[,23], sizes=c(1:22), rfeControl=control)
predictors(sfvar)
plot(sfvar, type=c("g", "o"))

sfcopy2 <- sfcopy %>% select(FTM ,TS ,FTr, FGP, FTA, FTP, X3PAr, PF, X3PP, STL, X3PM, AST, TOV, PER, X3PA, ORB, DRB, Age, BLK, PTS, OWS, pCap)

pfvar <- rfe(pfcopy[,1:22], pfcopy[,23], sizes=c(1:22), rfeControl=control)
predictors(pfvar)
plot(pfvar, type=c("g", "o"))

#rfe chooses all vars for pf, no need to make copy

cvar <- rfe(ccopy[,1:22], ccopy[,23], sizes=c(1:22), rfeControl=control)
predictors(cvar)
plot(cvar, type=c("g", "o"))

ccopy2 <- ccopy %>% select(FGP, X3PAr, TS, FTM, STL, FTA, FTr, BLK, X3PM, AST, X3PP, Age, PTS,PER, FTP, X3PA, TOV, DRB, ORB, DWS, OWS, USG, PF, pCap)
```


```{r, echo = FALSE, message=FALSE}
#I split the second copy data set into train and test for all positions
smp_sizepg2 <- floor(0.75 * nrow(pgcopy2))
train_indpg2 <- sample(seq_len(nrow(pgcopy2)), size = smp_sizepg2)
trainpg2 <- pgcopy2[train_indpg2, ]
testpg2 <- pgcopy2[-train_indpg2, ]

smp_sizesg2 <- floor(0.75 * nrow(sgcopy2))
train_indsg2 <- sample(seq_len(nrow(sgcopy2)), size = smp_sizesg2)
trainsg2 <- sgcopy2[train_indsg2, ]
testsg2 <- sgcopy2[-train_indsg2, ]

smp_sizesf2 <- floor(0.75 * nrow(sfcopy2))
train_indsf2 <- sample(seq_len(nrow(sfcopy2)), size = smp_sizesf2)
trainsf2 <- sfcopy2[train_indsf2, ]
testsf2 <- sfcopy2[-train_indsf2, ]

smp_sizecenter2 <- floor(0.75 * nrow(ccopy2))
train_indcenter2 <- sample(seq_len(nrow(ccopy2)), size = smp_sizecenter2)
traincenter2 <- ccopy2[train_indcenter2, ]
testcenter2 <- ccopy2[-train_indcenter2, ]
```

Ridge
```{r, echo = FALSE, message=FALSE}
#Ridge for PG
xpgtrain2 <- model.matrix(pCap ~.^2 , trainpg2)[,-1]
xpgtest2 <- model.matrix(pCap ~.^2 , testpg2)[,-1]
ypgtrain2 <- trainpg2$pCap
ypgtest2 <- testpg2$pCap


cv_ridgepg <- cv.glmnet(xpgtrain2, ypgtrain2, alpha = 0, lambda = lambdas)
optimal_lambdapg <- cv_ridgepg$lambda.min
ridge_regpg = glmnet(xpgtrain2, ypgtrain2, alpha = 0, family = 'gaussian', lambda = optimal_lambdapg)
predpgtrain2 <- predict(ridge_regpg, s = optimal_lambdapg, newx = xpgtrain2)
predpgtest2 <- predict(ridge_regpg, s = optimal_lambdapg, newx = xpgtest2)


#STORE RESULTS INTO THE DATAFRAME, REPEAT FOR ALL POSITIONS
ridgePGtrain <- data.frame(Model = "ridgePGtrain", R2 = rsq(ypgtrain2, predpgtrain2), RMSE = RMSE(ypgtrain2, predpgtrain2), MAE = MAE(ypgtrain2, predpgtrain2))
ridgePGtest <- data.frame(Model = "ridgePGtest", R2 = rsq(ypgtest2, predpgtest2), RMSE = RMSE(ypgtest2, predpgtest2), MAE = MAE(ypgtest2, predpgtest2))

modelResults <- rbind(modelResults, ridgePGtrain)
modelResults <- rbind(modelResults, ridgePGtest)
```

```{r, echo = FALSE, message=FALSE}
#Ridge for SG
xsgtrain2 <- model.matrix(pCap ~.^2 , trainsg2)[,-1]
xsgtest2 <- model.matrix(pCap ~.^2 , testsg2)[,-1]
ysgtrain2 <- trainsg2$pCap
ysgtest2 <- testsg2$pCap


cv_ridgesg <- cv.glmnet(xsgtrain2, ysgtrain2, alpha = 0, lambda = lambdas)
optimal_lambdasg <- cv_ridgesg$lambda.min
ridge_regsg = glmnet(xsgtrain2, ysgtrain2, alpha = 0, family = 'gaussian', lambda = optimal_lambdasg)
predsgtrain2 <- predict(ridge_regsg, s = optimal_lambdasg, newx = xsgtrain2)
predsgtest2 <- predict(ridge_regsg, s = optimal_lambdasg, newx = xsgtest2)


ridgeSGtrain <- data.frame(Model = "ridgeSGtrain", R2 = rsq(ysgtrain2, predsgtrain2), RMSE = RMSE(ysgtrain2, predsgtrain2), MAE = MAE(ysgtrain2, predsgtrain2))
ridgeSGtest <- data.frame(Model = "ridgeSGtest", R2 = rsq(ysgtest2, predsgtest2), RMSE = RMSE(ysgtest2, predsgtest2), MAE = MAE(ysgtest2, predsgtest2))

modelResults <- rbind(modelResults, ridgeSGtrain)
modelResults <- rbind(modelResults, ridgeSGtest)
```

```{r, echo = FALSE, message=FALSE}
#Ridge for SF
xsftrain2 <- model.matrix(pCap ~.^2 , trainsf2)[,-1]
xsftest2 <- model.matrix(pCap ~.^2 , testsf2)[,-1]
ysftrain2 <- trainsf2$pCap
ysftest2 <- testsf2$pCap


cv_ridgesf <- cv.glmnet(xsftrain2, ysftrain2, alpha = 0, lambda = lambdas)
optimal_lambdasf <- cv_ridgesf$lambda.min
ridge_regsf = glmnet(xsftrain2, ysftrain2, alpha = 0, family = 'gaussian', lambda = optimal_lambdasf)
predsftrain2 <- predict(ridge_regsf, s = optimal_lambdasf, newx = xsftrain2)
predsftest2 <- predict(ridge_regsf, s = optimal_lambdasf, newx = xsftest2)


ridgeSFtrain <- data.frame(Model = "ridgeSFtrain", R2 = rsq(ysftrain2, predsftrain2), RMSE = RMSE(ysftrain2, predsftrain2), MAE = MAE(ysftrain2, predsftrain2))
ridgeSFtest <- data.frame(Model = "ridgeSFtest", R2 = rsq(ysftest2, predsftest2), RMSE = RMSE(ysftest2, predsftest2), MAE = MAE(ysftest2, predsftest2))

modelResults <- rbind(modelResults, ridgeSFtrain)
modelResults <- rbind(modelResults, ridgeSFtest)
```

```{r, echo = FALSE, message=FALSE}
#Ridge for PF
xpftrain <- model.matrix(pCap ~.^2 , trainpf)[,-1]
xpftest <- model.matrix(pCap ~.^2 , testpf)[,-1]
ypftrain <- trainpf$pCap
ypftest <- testpf$pCap

cv_ridgepf <- cv.glmnet(xpftrain, ypftrain, alpha = 0, lambda = lambdas)
optimal_lambdapf <- cv_ridgepf$lambda.min
ridge_regpf = glmnet(xpftrain, ypftrain, alpha = 0, family = 'gaussian', lambda = optimal_lambdapf)
predpftrain2 <- predict(ridge_regpf, s = optimal_lambdapf, newx = xpftrain)
predpftest2 <- predict(ridge_regpf, s = optimal_lambdapf, newx = xpftest)


ridgePFtrain <- data.frame(Model = "ridgePFtrain", R2 = rsq(ypftrain, predpftrain2), RMSE = RMSE(ypftrain, predpftrain2), MAE = MAE(ypftrain, predpftrain2))
ridgePFtest <- data.frame(Model = "ridgePFtest", R2 = rsq(ypftest, predpftest2), RMSE = RMSE(ypftest, predpftest2), MAE = MAE(ypftest, predpftest2))

modelResults <- rbind(modelResults, ridgePFtrain)
modelResults <- rbind(modelResults, ridgePFtest)
```

```{r, echo = FALSE, message=FALSE}
#Ridge for Center
xctrain2 <- model.matrix(pCap ~.^2 , traincenter2)[,-1]
xctest2 <- model.matrix(pCap ~.^2 , traincenter2)[,-1]
yctrain2 <- traincenter2$pCap
yctest2 <- traincenter2$pCap

cv_ridgec <- cv.glmnet(xctrain2, yctrain2, alpha = 0, lambda = lambdas)
optimal_lambdac <- cv_ridgec$lambda.min
ridge_regc = glmnet(xctrain2, yctrain2, alpha = 0, family = 'gaussian', lambda = optimal_lambdac)
predctrain2 <- predict(ridge_regsf, s = optimal_lambdasf, newx = xsftrain2)
predctest2 <- predict(ridge_regsf, s = optimal_lambdasf, newx = xsftest2)

ridgeCtrain <- data.frame(Model = "ridgeCtrain", R2 = rsq(ysftrain2, predctrain2), RMSE = RMSE(ysftrain2, predctrain2), MAE = MAE(ysftrain2, predctrain2))
ridgeCtest <- data.frame(Model = "ridgeCtest", R2 = rsq(ysftest2, predctest2), RMSE = RMSE(ysftest2, predctest2), MAE = MAE(ysftest2, predctest2))

modelResults <- rbind(modelResults, ridgeCtrain)
modelResults <- rbind(modelResults, ridgeCtest)

(0.04492896+0.05134604+0.05212773+0.05338383+0.05638042)/5
(0.6149988+0.5741679+0.5446139+0.6481659+0.6015756)/5
(0.04950405+0.05330211+0.05663691+0.05818258+0.05663691)/5
(.5697660+0.6463589+0.5337727+0.6537358+0.5337727)/5
(0.04533099+0.05212389+0.05311899+0.05358819+0.05902619)/5
(0.6080780+0.5611681+0.5271300+0.6454670+0.5633044)/5

(0.04492903+0.05131513+0.05212906+0.05337268+0.05637771)/5
(0.6149977+0.5746803+0.5445907+0.6483129+0.6016138)/5
(0.05371475+0.04546715+0.05702096+0.05310470+0.05702096)/5
(0.5951987+0.6692783+0.5013722+0.6518355+0.5013722)/5
```

Elastic Net
```{r, echo = FALSE, message=FALSE}
#Elastic Net PG
xpgtrain <- model.matrix(pCap ~.^2 , trainpg)[,-1]
xpgtest <- model.matrix(pCap ~.^2 , testpg)[,-1]
ypgtrain <- trainpg$pCap
ypgtest <- testpg$pCap

train_cont <- trainControl(method = "repeatedcv", number = 5, repeats = 5,search = "random", verboseIter = TRUE)
elastic_regpg <- train(pCap ~ .^2,data = trainpg, method = "glmnet", preProcess = c("center", "scale"), tuneLength = 10, trControl = train_cont)

elastic_regpg$bestTune

predictionspgtrain3 <- predict(elastic_regpg, xpgtrain)
predictionspgtest3 <- predict(elastic_regpg, xpgtest)

enPGtrain <- data.frame(Model = "enPGtrain", R2 = rsq(ypgtrain, predictionspgtrain3), RMSE = RMSE(ypgtrain, predictionspgtrain3), MAE = MAE(ypgtrain, predictionspgtrain3))
enPGtest <- data.frame(Model = "enPGtest", R2 = rsq(ypgtest, predictionspgtest3), RMSE = RMSE(ypgtest, predictionspgtest3), MAE = MAE(ypgtest, predictionspgtest3))

modelResults <- rbind(modelResults, enPGtrain)
modelResults <- rbind(modelResults, enPGtest)
```

```{r, echo = FALSE, message=FALSE}
#Elastic Net for SG
xsgtrain <- model.matrix(pCap ~.^2 , trainsg)[,-1]
xsgtest <- model.matrix(pCap ~.^2 , testsg)[,-1]
ysgtrain <- trainsg$pCap
ysgtest <- testsg$pCap

train_cont <- trainControl(method = "repeatedcv", number = 5, repeats = 5,search = "random", verboseIter = TRUE)
elastic_regsg <- train(pCap ~ .^2,data = trainsg, method = "glmnet", preProcess = c("center", "scale"), tuneLength = 10, trControl = train_cont)

elastic_regsg$bestTune

predictionssgtrain3 <- predict(elastic_regsg, xsgtrain)
predictionssgtest3 <- predict(elastic_regsg, xsgtest)

enSGtrain <- data.frame(Model = "enSGtrain", R2 = rsq(ysgtrain, predictionssgtrain3), RMSE = RMSE(ysgtrain, predictionssgtrain3), MAE = MAE(ysgtrain, predictionssgtrain3))
enSGtest <- data.frame(Model = "enSGtest", R2 = rsq(ysgtest, predictionssgtest3), RMSE = RMSE(ysgtest, predictionssgtest3), MAE = MAE(ysgtest, predictionssgtest3))

modelResults <- rbind(modelResults, enSGtrain)
modelResults <- rbind(modelResults, enSGtest)
```

```{r, echo = FALSE, message=FALSE}
#Elastic Net for SF
xsftrain <- model.matrix(pCap ~.^2 , trainsf)[,-1]
xsftest <- model.matrix(pCap ~.^2 , testsf)[,-1]
ysftrain <- trainsf$pCap
ysftest <- testsf$pCap

train_cont <- trainControl(method = "repeatedcv", number = 5, repeats = 5,search = "random", verboseIter = TRUE)
elastic_regsf <- train(pCap ~ .^2,data = trainsf, method = "glmnet", preProcess = c("center", "scale"), tuneLength = 10, trControl = train_cont)

elastic_regsf$bestTune

predictionssftrain3 <- predict(elastic_regsf, xsftrain)
predictionssftest3 <- predict(elastic_regsf, xsftest)

enSFtrain <- data.frame(Model = "enSFtrain", R2 = rsq(ysftrain, predictionssftrain3), RMSE = RMSE(ysftrain, predictionssftrain3), MAE = MAE(ysftrain, predictionssftrain3))
enSFtest <- data.frame(Model = "enSFtest", R2 = rsq(ysftest, predictionssftest3), RMSE = RMSE(ysftest, predictionssftest3), MAE = MAE(ysftest, predictionssftest3))

modelResults <- rbind(modelResults, enSFtrain)
modelResults <- rbind(modelResults, enSFtest)
```

```{r, echo = FALSE, message=FALSE}
#Elastic Net for PF
xpftrain <- model.matrix(pCap ~.^2 , trainpf)[,-1]
xpftest <- model.matrix(pCap ~.^2 , testpf)[,-1]
ypftrain <- trainpf$pCap
ypftest <- testpf$pCap

train_cont <- trainControl(method = "repeatedcv", number = 5, repeats = 5,search = "random", verboseIter = TRUE)
elastic_regpf <- train(pCap ~ .^2,data = trainpf, method = "glmnet", preProcess = c("center", "scale"), tuneLength = 10, trControl = train_cont)

elastic_regpf$bestTune

predictionspftrain3 <- predict(elastic_regpf, xpftrain)
predictionspftest3 <- predict(elastic_regpf, xpftest)

enPFtrain <- data.frame(Model = "enPFtrain", R2 = rsq(ypftrain, predictionspftrain3), RMSE = RMSE(ypftrain, predictionspftrain3), MAE = MAE(ypftrain, predictionspftrain3))
enPFtest <- data.frame(Model = "enPFtest", R2 = rsq(ypftest, predictionspftest3), RMSE = RMSE(ypftest, predictionspftest3), MAE = MAE(ypftest, predictionspftest3))

modelResults <- rbind(modelResults, enPFtrain)
modelResults <- rbind(modelResults, enPFtest)
```

```{r, echo = FALSE, message=FALSE}
#Elastic Net for Center
xctrain <- model.matrix(pCap ~.^2 , traincenter)[,-1]
xctest <- model.matrix(pCap ~.^2 , testcenter)[,-1]
yctrain <- traincenter$pCap
yctest <- testcenter$pCap

train_cont <- trainControl(method = "repeatedcv", number = 5, repeats = 5,search = "random", verboseIter = TRUE)
elastic_regc <- train(pCap ~ .^2,data = traincenter, method = "glmnet", preProcess = c("center", "scale"), tuneLength = 10, trControl = train_cont)

elastic_regc$bestTune
coef(elastic_regc$finalModel, elastic_regc$bestTune$lambda)
predictionsctrain3 <- predict(elastic_regc, xctrain)
predictionsctest3 <- predict(elastic_regc, xctest)

enCtrain <- data.frame(Model = "enCtrain", R2 = rsq(yctrain, predictionsctrain3), RMSE = RMSE(yctrain, predictionsctrain3), MAE = MAE(yctrain, predictionsctrain3))
enCtest <- data.frame(Model = "enCtest", R2 = rsq(yctest, predictionsctest3), RMSE = RMSE(yctest, predictionsctest3), MAE = MAE(yctest, predictionsctest3))

modelResults <- rbind(modelResults, enCtrain)
modelResults <- rbind(modelResults, enCtest)

```

```{r}
#here im just checking which variables were selected by each elastic net model
coef(elastic_regpg$finalModel, elastic_regpg$bestTune$lambda)
coef(elastic_regsg$finalModel, elastic_regsg$bestTune$lambda)
coef(elastic_regsf$finalModel, elastic_regsf$bestTune$lambda)
coef(elastic_regpf$finalModel, elastic_regpf$bestTune$lambda)
coef(elastic_regc$finalModel, elastic_regc$bestTune$lambda)
```

```{r}
#Here I am adding the predicted values from both the training and test sets back into the original dataset for comparison

finalResults1 <- cbind(trainpg, "a" = round(predpgtrain,8))
names(finalResults1)[names(finalResults1) == '1'] <- "Predicted pCap"
finalResults1$Diff <- round(finalResults1$Predicted - finalResults1$pCap, 8) 

finalResults2 <- cbind(testpg, "a" = round(predpgtest,8))
names(finalResults2)[names(finalResults2) == '1'] <- "Predicted pCap"
finalResults2$Diff <- round(finalResults2$Predicted - finalResults2$pCap, 8) 

finalResults3 <- cbind(trainsg, "a" = round(predsgtrain,8))
names(finalResults3)[names(finalResults3) == '1'] <- "Predicted pCap"
finalResults3$Diff <- round(finalResults3$Predicted - finalResults3$pCap, 8) 

finalResults4 <- cbind(testsg, "a" = round(predsgtest,8))
names(finalResults4)[names(finalResults4) == '1'] <- "Predicted pCap"
finalResults4$Diff <- round(finalResults4$Predicted - finalResults4$pCap, 8) 

finalResults5 <- cbind(trainsf, "a" = round(predsftrain,8))
names(finalResults5)[names(finalResults5) == '1'] <- "Predicted pCap"
finalResults5$Diff <- round(finalResults5$Predicted - finalResults5$pCap, 8) 

finalResults6 <- cbind(testsf, "a" = round(predsftest,8))
names(finalResults6)[names(finalResults6) == '1'] <- "Predicted pCap"
finalResults6$Diff <- round(finalResults6$Predicted - finalResults6$pCap, 8) 

finalResults7 <- cbind(trainpf, "a" = round(predpftrain,8))
names(finalResults7)[names(finalResults7) == '1'] <- "Predicted pCap"
finalResults7$Diff <- round(finalResults7$Predicted - finalResults7$pCap, 8) 

finalResults8 <- cbind(testpf, "a" = round(predpftest,8))
names(finalResults8)[names(finalResults8) == '1'] <- "Predicted pCap"
finalResults8$Diff <- round(finalResults8$Predicted - finalResults8$pCap, 8) 

finalResults9 <- cbind(traincenter, "a" = round(predctrain,8))
names(finalResults9)[names(finalResults9) == '1'] <- "Predicted pCap"
finalResults9$Diff <- round(finalResults9$Predicted - finalResults9$pCap, 8) 

finalResults10 <- cbind(testcenter, "a" = round(predctest,8))
names(finalResults10)[names(finalResults10) == '1'] <- "Predicted pCap"
finalResults10$Diff <- round(finalResults10$Predicted - finalResults10$pCap, 8) 


#Here I am combining all of them into one data set
finalResults <- rbind(finalResults1, finalResults2[!rownames(finalResults2) %in% rownames(finalResults1),])
finalResults <- rbind(finalResults, finalResults3[!rownames(finalResults3) %in% rownames(finalResults),])
finalResults <- rbind(finalResults, finalResults4[!rownames(finalResults4) %in% rownames(finalResults),])
finalResults <- rbind(finalResults, finalResults5[!rownames(finalResults5) %in% rownames(finalResults),])
finalResults <- rbind(finalResults, finalResults6[!rownames(finalResults6) %in% rownames(finalResults),])
finalResults <- rbind(finalResults, finalResults7[!rownames(finalResults7) %in% rownames(finalResults),])
finalResults <- rbind(finalResults, finalResults8[!rownames(finalResults8) %in% rownames(finalResults),])
finalResults <- rbind(finalResults, finalResults9[!rownames(finalResults9) %in% rownames(finalResults),])
finalResults <- rbind(finalResults, finalResults10[!rownames(finalResults10) %in% rownames(finalResults),])

#Checking the most under and over valued players (by our model's standard)
ordered <- finalResults[order(-finalResults$Diff),]
best <- head(ordered, 10)
worst <- tail(ordered, 10)
best <- best %>% select(pCap, "Predicted pCap", Diff)
worst <- worst %>% select(pCap, "Predicted pCap", Diff)

copy1 <- finalResults
copy1 <- cbind(Player = rownames(copy1), copy1)
rownames(copy1) <- NULL
copy2 <- nba
copy2 <- cbind(Player = rownames(copy2), copy2)
rownames(copy2) <- NULL

copy3 <- merge(x = copy2, copy1[,c("Player", "Predicted pCap", "Diff")], by = "Player", all.x=TRUE)
copy3 <- subset(copy3, select = -c(Cap, Experience))

library(tm)

copy4 <- copy3
x <- copy4$Player
x <- removeNumbers(x)
copy4$Player <- x

write.csv(copy4, "nbafinaldata.csv")
```

```{r}
#reading in 2021 nba data to predict salary for 2022
nba2021 <- read.csv("nbadata2021.csv")
nba2021$X <- NULL
rownames(nba2021) <- nba2021[,1]
nba2021 <- nba2021[,-1]

nba2021$FA <- "N"
nba2021$FA[nba2021$Salary == 0] <- "Y"
nba2021$pCap <- nba2021$Salary / 112000000
```

```{r}
pg2021 <- filter(nba2021, Pos == "PG" | Pos == "PG-SG" | Pos == "SG-PG" | Pos == "PG-SF" )
sg2021 <- filter(nba2021, Pos == "SG" | Pos == "SF-SG" | Pos == "SG-PG" | Pos == "SG-PF" | Pos == "PG-SG" | Pos == "SG-SF")
sf2021 <- filter(nba2021, Pos == "SF" | Pos == "PG-SF" | Pos == "PF-SF" | Pos == "SF-SG" | Pos == "SF-PF" | Pos == "SG-SF" | Pos == "SF-C" )
pf2021 <- filter(nba2021, Pos == "PF" | Pos == "SF-PF" | Pos == "PF-SF" | Pos == "PF-C" | Pos == "C-PF" )
c2021 <- filter(nba2021, Pos == "C" | Pos == "C-PF" | Pos == "PF-C" | Pos == "SF-C" )

nbacopy2021 <- subset(nba2021, select = -c(Season, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, Salary2021, FA))

pgcopy2021 <- subset(pg2021, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, Salary2021, FA))

sgcopy2021 <- subset(sg2021, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary,Salary2021, FA))

sfcopy2021 <- subset(sf2021, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary,Salary2021, FA))

pfcopy2021 <- subset(pf2021, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG,  BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary, Salary2021, FA))

ccopy2021 <- subset(c2021, select = -c(Season, Pos, Tm, G, GS, MP, FG, FGA, X2PM, X2PA, X2PP, TRB, eFG, BPM, OBPM, DBPM, VORP, WS, WS48, ORBP, DRBP, TRBP, ASTP, STLP, BLKP, TOVP, Salary,Salary2021, FA))
```

```{r}
xpg2021 <- model.matrix(pCap ~.^2 , pgcopy2021)[,-1]
ypg2021 <- pgcopy2021$pCap

predpg2021 <- predict(lassopg, newx = xpg2021)
finalResultspg <- cbind(pg2021, "a" = round(predpg2021,8))

xsg2021 <- model.matrix(pCap ~.^2 , sgcopy2021)[,-1]
ysg2021 <- sgcopy2021$pCap

predsg2021 <- predict(lassosg, newx = xsg2021)
finalResultssg <- cbind(sg2021, "a" = round(predsg2021,8))

xsf2021 <- model.matrix(pCap ~.^2 , sfcopy2021)[,-1]
ysf2021 <- sfcopy2021$pCap

predsf2021 <- predict(lassosf, newx = xsf2021)
finalResultssf <- cbind(sf2021, "a" = round(predsf2021,8))

xpf2021 <- model.matrix(pCap ~.^2 , pfcopy2021)[,-1]
ypf2021 <- pfcopy2021$pCap

predpf2021 <- predict(lassopf, newx = xpf2021)
finalResultspf <- cbind(pf2021, "a" = round(predpf2021,8))

xc2021 <- model.matrix(pCap ~.^2 , ccopy2021)[,-1]
yc2021 <- ccopy2021$pCap

predc2021 <- predict(lassoc, newx = xc2021)
finalResultsc <- cbind(c2021, "a" = round(predc2021,8))

finalResults2021 <- rbind(finalResultspg, finalResultssg[!rownames(finalResultssg) %in% rownames(finalResultspg),])
finalResults2021 <- rbind(finalResults2021, finalResultssf[!rownames(finalResultssf) %in% rownames(finalResults2021),])
finalResults2021 <- rbind(finalResults2021, finalResultspf[!rownames(finalResultspf) %in% rownames(finalResults2021),])
finalResults2021 <- rbind(finalResults2021, finalResultsc[!rownames(finalResultsc) %in% rownames(finalResults2021),])
```

```{r}
finalResults2021copy <- finalResults2021
finalResults2021copy <- subset(finalResults2021copy, MP > 10)
finalResults2021copy <- subset(finalResults2021copy, select = -c(Season, Pos, Age, Tm, Salary2021, Salary, FA, pCap, s0))
standard2021<- normalize(finalResults2021copy, method = "standardize")

res.dist <- get_dist(standard2021, stand = TRUE, method = "euclidean")
fviz_dist(res.dist, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"),lab_size= 2)
fviz_nbclust(standard2021, kmeans, method = "wss")
fviz_nbclust(standard2021, kmeans, method = "silhouette")
fviz_nbclust(standard2021, kmeans, method = "gap_stat")

km.res <- kmeans(standard2021,10, nstart = 100)

fviz_cluster(km.res, standard2021, ellipse = TRUE, ellipse.alpha= 0.1,
             palette = "jco",repel = TRUE, ggtheme = theme_minimal(), 
             main= FALSE, xlab= FALSE, ylab = FALSE,
             labelsize= 9,lwd=2
             )

Clusters=data.frame(sort(km.res$cluster))
km.res
copyCluster <- Clusters

copyCluster <- cbind(Player = rownames(copyCluster), copyCluster)
rownames(copyCluster) <- NULL

finalcopy2 <- cbind(Player = rownames(finalResults2021), finalResults2021)
rownames(finalcopy2) <- NULL

final2021 <- merge(x = finalcopy2, copyCluster[,c("Player", "sort.km.res.cluster.")], by = "Player", all.x=TRUE)
write.csv(final2021, "nbapredfinal2021.csv")
```
